name: discover-podcast-feeds

on:
  workflow_dispatch:
  # schedule:
  #  - cron: '0 10 * * *'

jobs:
  update-feeds:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.7'
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute discovery script
        run: python discover_feeds.py
          
      - name: Auto-commit changes and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Configuration auto-update
          commit_author: Podcast Auto-Discovery <actions@github.com>
          repository: .
          file_pattern: 'podcasts.json'
